services:
  - type: web
    name: insulin-resistance-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m src.train
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
