services:
  - type: web
    name: insulin-resistance-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
